/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import compositions.Account;
import compositions.Database;
import compositions.PersonalInfo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 2ndyrGroupC
 */
public class CreatePersonalInfo extends javax.swing.JFrame {

    /**
     * Creates new form CreatePersonalInfo
     */
//    static Account account = null;
    private Database db = new Database();
    ChoiceEnrollment mainMenu;

    public CreatePersonalInfo(Account accounts) {
        initComponents();
    }

    public CreatePersonalInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jTextField_lastname = new javax.swing.JTextField();
        jTextField_age = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Personal Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTextField_firstname.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_firstname.setText("Firstname");
        jTextField_firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_firstnameFocusLost(evt);
            }
        });

        jTextField_lastname.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_lastname.setText("Lastname");
        jTextField_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_lastnameFocusLost(evt);
            }
        });

        jTextField_age.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_age.setText("Age");
        jTextField_age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_ageFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 51));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_firstname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_lastname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_firstnameFocusGained
        if (jTextField_firstname.getText().equals("Firstname")) {
            jTextField_firstname.setText("");
        }
        jTextField_firstname.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jTextField_firstnameFocusGained

    private void jTextField_firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_firstnameFocusLost
        if (jTextField_firstname.getText().equals("")) {
            jTextField_firstname.setText("Firstname");
            jTextField_firstname.setForeground(new Color(102, 102, 102));
        } else {
        }
    }//GEN-LAST:event_jTextField_firstnameFocusLost

    private void jTextField_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_lastnameFocusGained
        if (jTextField_lastname.getText().equals("Lastname")) {
            jTextField_lastname.setText("");
        }
        jTextField_lastname.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jTextField_lastnameFocusGained

    private void jTextField_lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_lastnameFocusLost
        if (jTextField_lastname.getText().equals("")) {
            jTextField_lastname.setText("Lastname");
            jTextField_lastname.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_jTextField_lastnameFocusLost

    private void jTextField_ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ageFocusGained
        if (jTextField_age.getText().equals("Age")) {
            jTextField_age.setText("");
        }
        jTextField_age.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jTextField_ageFocusGained

    private void jTextField_ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_ageFocusLost
        if (jTextField_age.getText().equals("")) {
            jTextField_age.setText("Age");
            jTextField_age.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_jTextField_ageFocusLost

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int dialogRes = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel?");
        if (dialogRes == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new ChoiceEnrollment().setVisible(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String firstname = jTextField_firstname.getText();
        String lastname = jTextField_lastname.getText();
        String age = jTextField_age.getText();
        if (jTextField_firstname.getText().equals("") || jTextField_firstname.getText().equals("Firstname")
                || jTextField_lastname.getText().equals("") || jTextField_lastname.getText().equals("Lastname")
                || jTextField_age.getText().equals("") || jTextField_age.getText().equals("Age")) {
            JOptionPane.showMessageDialog(this, "Please fill all the field!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {

            for (int i = 0; i < jTextField_firstname.getText().length(); i++) {
                char c = jTextField_firstname.getText().charAt(i);
                if (Character.isDigit(c) || jTextField_firstname.getText().equals(" ")) {
                    JOptionPane.showMessageDialog(this, "Invalid firstname input! Try another one", "Error",
                            JOptionPane.ERROR_MESSAGE);
                    break;
                }
                for (int j = 0; j < jTextField_lastname.getText().length(); j++) {
                    char l = jTextField_lastname.getText().charAt(j);
                    if (Character.isDigit(l) || jTextField_lastname.getText().equals(" ")) {
                        JOptionPane.showMessageDialog(this, "Invalid lastname input! Try another one", "Error",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }
                if (jTextField_age.getText().matches("-?\\d+(\\.\\d+)?") == false) {
                    JOptionPane.showMessageDialog(this, "Age must be a number", "Error",
                            JOptionPane.ERROR_MESSAGE);
                    break;
                } else {
                    if (Integer.parseInt(jTextField_age.getText()) < 1) {
                        JOptionPane.showMessageDialog(this, "Age only 1 and above", "Error",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    } else {
                        System.out.println("Sucess");
                        PersonalInfo pi = new PersonalInfo();
                        pi.setfName(firstname);
                        pi.setlName(lastname);
                        pi.setAge(Integer.valueOf(age));
//                        account = new Account();
//                        account.setInfo(pi);

//                        int results[] = db.create(account);

//                        if (results[0] == 1 && results[1] == 1) {
//                            int dialogRes = JOptionPane.showConfirmDialog(this, "Information has been added successfully\n"
//                                    + "Do you want to add schedules?");
//                            if (dialogRes == JOptionPane.YES_OPTION) {
//
//                                account.setId(results[3]);
//                                CreateSchedule sched = new CreateSchedule(account);
//                                sched.setVisible(true);
//                                this.setVisible(false);
//
//                            } else {
//                                this.setVisible(false);
//                                new ChoiceEnrollment().setVisible(true);
//                            }
////
//                        } else {
//                            JOptionPane.showMessageDialog(this, "Save Failed !", "Error", JOptionPane.ERROR_MESSAGE);
//                        }
                        Connection conn = null;
                        Statement stmt = null;

                        try {
                            //STEP 2: Register JDBC driver
                            Class.forName("com.mysql.jdbc.Driver");
                            //STEP 3: Open a connection
                            System.out.println("Connecting to database...");
                            conn = DriverManager.getConnection("jdbc:mysql://localhost/chervdb", "root", "");

                            //STEP 4: Execute a query
                            PreparedStatement pst1 = conn.prepareStatement("select max(id)+1 from tbl_info");
                            ResultSet rSet = pst1.executeQuery();
                            String user_id = "";
                            while (rSet.next()) {
                                user_id = rSet.getString(1);
                            }
                            PreparedStatement pst = conn.prepareStatement("select max(id) from tbl_accounts");
                            ResultSet rs = pst.executeQuery();
                            String acc_id = "";
                            while (rs.next()) {
                                acc_id = rs.getString(1);
                            }
                            System.out.println("Creating statement...");
                            stmt = conn.createStatement();
                            String sql;
                            //I STOPPED HERE FOR SVING TO DATABASE
                            sql = "INSERT INTO tbl_info VALUES('" + user_id + "','"+acc_id+"','" + jTextField_firstname.getText() + "','"
                                    + jTextField_lastname.getText() + "','" + jTextField_age.getText() + "')";

                            stmt.executeUpdate(sql);
                            int dialogRes = JOptionPane.showConfirmDialog(this, "Personal information is added successfully!\n"
                                    + "Do you want to add schedule?");
                            if (dialogRes == JOptionPane.YES_OPTION) {
                                this.setVisible(false);
                                new CreateSchedule().setVisible(true);
                            } else {
                                this.setVisible(false);
                                new ChoiceEnrollment().setVisible(true);
                            }
                            stmt.close();
                            conn.close();
                        } catch (SQLException se) {
                            se.printStackTrace();
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
                        }//end try
                        System.out.println("Goodbye!");
                        break;
                    }
                }
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePersonalInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_lastname;
    // End of variables declaration//GEN-END:variables
}
