/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import compositions.Database;
import compositions.PersonalInfo;
import compositions.Schedule;
import compositions.Validation;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 2ndyrGroupC
 */
public class UpdateChoice extends javax.swing.JFrame {

    /**
     * Creates new form UpdateChoice
     */
    Validation validate = new Validation();
    Database db = new Database();

    public UpdateChoice() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_updateinfo = new javax.swing.JButton();
        jButton_updatesched = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Information by:");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton_updateinfo.setBackground(new java.awt.Color(255, 102, 0));
        jButton_updateinfo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton_updateinfo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_updateinfo.setText("Personal Information");
        jButton_updateinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_updateinfoMouseClicked(evt);
            }
        });

        jButton_updatesched.setBackground(new java.awt.Color(255, 102, 0));
        jButton_updatesched.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton_updatesched.setForeground(new java.awt.Color(255, 255, 255));
        jButton_updatesched.setText("Schedule");
        jButton_updatesched.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_updateschedMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_updatesched, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_updateinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_updateinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_updatesched, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.setVisible(false);
        new ChoiceEnrollment().setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton_updateinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_updateinfoMouseClicked

        // TODO add your handling code here:
        JTextField accId = new JTextField();
        JTextField fname1 = new JTextField();
        JTextField lname1 = new JTextField();
        JTextField age = new JTextField();
        Object[] message = {
            "Account Id", accId,
            "Firstname:", fname1,
            "Lastname:", lname1,
            "Age:", age
        };
        this.setVisible(false);

        if (JOptionPane.showConfirmDialog(null, message, "Update Schedule", JOptionPane.OK_CANCEL_OPTION) == 0) {
            boolean valid = true;
            String errMessage = "";

            try {
                if (!validate.checkInt(accId.getText())) {
                    valid = false;
                    this.setVisible(true);
                    accId.setText("");
                    age.setText("");
                    fname1.setText("");
                    lname1.setText("");
                    age.setText("");
                    errMessage += "Invalid Account Number\n";
                } else if (!validate.checkUsername(fname1.getText())) {
                    valid = false;
                    this.setVisible(true);
                    fname1.setText("");
                    lname1.setText("");
                    age.setText("");
                    errMessage += "Invalid Firstame!\n";
                } else if (!validate.checkUsername(lname1.getText())) {
                    valid = false;
                    this.setVisible(true);
                    fname1.setText("");
                    lname1.setText("");
                    age.setText("");
                    errMessage += "Invalid Lastame!\n";
                } else if (!validate.checkInt(age.getText())) {
                    valid = false;
                    this.setVisible(true);
                    age.setText("");
                    errMessage += "Invalid Age!";
                }
                if (valid) {
                    PersonalInfo info = new PersonalInfo();
                    info.setAccId(Integer.valueOf(accId.getText()));
                    info.setfName(fname1.getText());
                    info.setlName(lname1.getText());
                    info.setAge(Integer.valueOf(age.getText()));
                    try {
                        if (!db.infoUpdate(Integer.valueOf(accId.getText()), info)) {
                            JOptionPane.showMessageDialog(null, "Account you want to update does'nt exist!", "Error!", JOptionPane.ERROR_MESSAGE);
                            this.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Information Successfully Updated", "Saved!", JOptionPane.NO_OPTION);
                            this.setVisible(true);
                        }

                    } catch (IOException ex) {
                        System.out.println(ex.getMessage());
                        JOptionPane.showMessageDialog(null, "Something went wrong...", "Error!", JOptionPane.ERROR_MESSAGE);

                    }
                } else {
                    throw new Exception(errMessage);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, errMessage, "Error!", JOptionPane.ERROR_MESSAGE);
                this.setVisible(true);
            }

        } else {
            this.setVisible(false);
            new UpdateChoice().setVisible(true);
        }


    }//GEN-LAST:event_jButton_updateinfoMouseClicked

    private void jButton_updateschedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_updateschedMouseClicked
        JTextField accId = new JTextField();
        JTextField course = new JTextField();
        JTextField year = new JTextField();
        JTextField subject = new JTextField();
        JTextField unit = new JTextField();
        JTextField schedule = new JTextField();
        Object[] message = {
            "Account Id", accId,
            "Subject:", subject,
            "Unit:", unit,
            "Schedule:", schedule
        };
        this.setVisible(false);

        if (JOptionPane.showConfirmDialog(null, message, "Update Schedule", JOptionPane.OK_CANCEL_OPTION) == 0) {
            boolean valid = true;
            String errMessage = "";
            try {
                if (!validate.checkInt(accId.getText())) {
                    valid = false;
                    this.setVisible(true);
                    accId.setText("");
                    subject.setText("");
                    unit.setText("");
                    schedule.setText("");
                    errMessage += "Invalid Account Number\n";
                } else if (!validate.checkInt(unit.getText())) {
                    valid = false;
                    this.setVisible(true);
                    unit.setText("");
                    schedule.setText("");
                    errMessage += "Invalid Units!";
                }
                if (valid) {
                    Schedule sched = new Schedule();

                    sched.setAll(Integer.valueOf(accId.getText()),
                            subject.getText(), Integer.valueOf(unit.getText()), schedule.getText());

                    try {
                        if (!db.schedUpdate(Integer.valueOf(accId.getText()), sched)) {
                            JOptionPane.showMessageDialog(null, "Account you want to update does'nt exist!", "Error!", JOptionPane.ERROR_MESSAGE);
                            this.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Schedule Successfully Updated", "Saved!", JOptionPane.NO_OPTION);
                            this.setVisible(true);
                        }

                    } catch (IOException ex) {
                        System.out.println(ex.getMessage());
                        JOptionPane.showMessageDialog(null, "Something went wrong...", "Error!", JOptionPane.ERROR_MESSAGE);

                    }
                } else {
                    throw new Exception(errMessage);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, errMessage, "Error!", JOptionPane.ERROR_MESSAGE);
                this.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton_updateschedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateChoice.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateChoice.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateChoice.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateChoice.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_updateinfo;
    private javax.swing.JButton jButton_updatesched;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
